### ISSUE TITLE
弹窗弹出后状态栏颜色变回去了

### ISSUE THREAD

**Issue by fumayer** [javakam/DialogManager#1]
大佬，就是我们全部的activity设置的状态栏上的文字颜色都是暗色（dark），用这个弹窗弹出后又变回白色（light）了，有办法解决吗

**Comment by javakam** [comment]
onShow时候改变下颜色应该可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月13日(周三) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [javakam/DialogManager] 弹窗弹出后状态栏颜色变回去了 (Issue #1)




 
大佬，就是我们全部的activity设置的状态栏上的文字颜色都是暗色（dark），用这个弹窗弹出后又变回白色（light）了，有办法解决吗

**Comment by fumayer** [comment]
好吧，我试过了全屏才能改变颜色，主题设置又和蒙层冲突。
