### ISSUE TITLE
老哥，依赖下不动啊

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [javakam/DialogManager#2]
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.github.javakam:dialog.bottomsheet:5.0.0, variant=com.github.javakam:dialog.bottomsheet:5.0.0, variantName=null, artifactFile=C:\Users\zhong\.gradle\caches\modules-2\files-2.1\com.github.javakam\dialog.bottomsheet\5.0.0\2d7a44b79bdb3a2e0d7b8e7d550d6b13c2b27232\dialog.bottomsheet-5.0.0.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=D:\AndroidStudioProjects\Smile})

必须要用@aar这种方式吗，下载不了😂

**Comment by SaltedFish-Extreme** [comment]
把settings.gradle里的仓库依赖加上阿里云的，重新同步了一遍，好像好了😂
````gradle
pluginManagement {
    repositories {
        maven{ url 'https://maven.aliyun.com/repository/google'}
        maven{ url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven{ url 'https://maven.aliyun.com/repository/public'}
        maven{ url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url "https://jitpack.io" }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven{ url 'https://maven.aliyun.com/repository/google'}
        maven{ url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven{ url 'https://maven.aliyun.com/repository/public'}
        maven{ url 'https://maven.aliyun.com/repository/jcenter'}
        maven { url "https://jitpack.io" }
        google()
        mavenCentral()
    }
}
````

**Comment by SaltedFish-Extreme** [comment]
老哥，又构建失败了😢
![image](https://user-images.githubusercontent.com/54784104/226534480-eccc8c95-0f94-41bc-8678-21a1cc1abab6.png)

**Comment by javakam** [comment]
😅抱歉刚看到哈... 搞定了不, 你把mavenCenter挪到最顶上试试

**Comment by SaltedFish-Extreme** [comment]
> 😅抱歉刚看到哈... 搞定了不, 你把mavenCenter挪到最顶上试试

好像可以，但是下载太慢了，而且构建过程还失败了😂

AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"D:\\Gradle\\caches\\transforms-3\\aeb7931cecbcc160fffe65b279ab4ec4\\transformed\\jetified-dialog.bottomsheet-5.0.0\\res\\layout\\bottom_sheet_fragment_recycler.xml","position":{"startLine":32}}],"original":"ERROR: D:\\Gradle\\caches\\transforms-3\\aeb7931cecbcc160fffe65b279ab4ec4\\transformed\\jetified-dialog.bottomsheet-5.0.0\\res\\layout\\bottom_sheet_fragment_recycler.xml:33: AAPT: error: resource dimen/dimen_ando_option_item_text (aka com.example.smile:dimen/dimen_ando_option_item_text) not found.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"D:\\Gradle\\caches\\transforms-3\\aeb7931cecbcc160fffe65b279ab4ec4\\transformed\\jetified-dialog.bottomsheet-5.0.0\\res\\layout\\bottom_sheet_fragment_recycler.xml","position":{"startLine":32}}],"original":"ERROR: D:\\Gradle\\caches\\transforms-3\\aeb7931cecbcc160fffe65b279ab4ec4\\transformed\\jetified-dialog.bottomsheet-5.0.0\\res\\layout\\bottom_sheet_fragment_recycler.xml:33: AAPT: error: resource color/color_ando_option_item_text (aka com.example.smile:color/color_ando_option_item_text) not found.\n    ","tool":"AAPT"}

![image](https://user-images.githubusercontent.com/54784104/232688080-21af6950-57e0-4876-8035-f4697881d9db.png)

**Comment by javakam** [comment]
可以试试 v6.0.0

**Comment by javakam** [comment]
热乎的刚更新

**Comment by SaltedFish-Extreme** [comment]
@javakam 老哥你确定吗😒要不你依赖里加上jitpack插件放jitpack上😂
![image](https://user-images.githubusercontent.com/54784104/233027944-5661cc85-b515-406e-a8bf-25f792546a36.png)
![image](https://user-images.githubusercontent.com/54784104/233027994-1bc103e6-6b59-4daa-943c-0785a84d2947.png)

**Comment by javakam** [comment]
刚传上去...

**Comment by SaltedFish-Extreme** [comment]
> 刚传上去...

这次下下来了core，usage和bottomsheet没下下来😢

![image](https://user-images.githubusercontent.com/54784104/233031929-e00256a4-81eb-4104-a45f-6a4ea58af549.png)

![image](https://user-images.githubusercontent.com/54784104/233032003-23289c81-a7af-4025-9d66-5ba20205746d.png)

**Comment by javakam** [comment]
再试试, 他这个有点延时刚传上去得过一会儿才会生效

**Comment by SaltedFish-Extreme** [comment]
> 再试试, 他这个有点延时刚传上去得过一会儿才会生效

不行啊，我又弄了一次还是这样😂

**Comment by javakam** [comment]
build.gradle 这么写试试:
```
repositories {
        //mavenLocal()
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
        maven { url "https://s01.oss.sonatype.org/content/groups/public" }
        maven { url "https://s01.oss.sonatype.org/content/repositories/releases" }
        maven { url "https://maven.aliyun.com/nexus/content/groups/public/" }
        maven { url "https://repo.spring.io/release" }
        maven { url "https://repository.jboss.org/maven2" }
        jcenter() // Warning: this repository is going to shut down soon
    }
```

**Comment by SaltedFish-Extreme** [comment]
@javakam 把mavenCentral移动到最上面这次下下来了，就是有点慢😂不知道为啥阿里的maven仓库放在最上面就下不下来这个，其他都可以😢

**Comment by javakam** [comment]
阿里同步仓库也需要一段时间扫描吧, 没有直接配置好方便

**Comment by SaltedFish-Extreme** [comment]
@javakam 还有老哥，你布局代码有问题啊😒我项目构建失败了😂
![image](https://user-images.githubusercontent.com/54784104/233242955-226a8689-ede9-418d-ad73-3d4f528d1efd.png)

**Comment by javakam** [comment]
试试别直接导入  `com.github.javakam:dialog.usage:6.0.0@aar` 这个包了,  改成本地导入使用吧。感觉这个包也没啥用, 不如放到 app 用例里面现用现搬方便。

**Comment by javakam** [comment]
这个包引入了没: implementation 'com.github.javakam:widget.optionview:6.0.0@aar'  //RecyclerView 实现的单/多选列表

![image](https://user-images.githubusercontent.com/15343661/233245582-ba8d6c00-11d9-4d83-9f6c-5891fea4dbb8.png)

**Comment by SaltedFish-Extreme** [comment]
没，那个包我看没用就没导入😂

**Comment by javakam** [comment]
我的锅注释不明确, 印象中之前是在一起的后来给分开了。 单/多选列表放到其他View上也可以是用, 未必是Dialog中。

**Comment by SaltedFish-Extreme** [comment]
😂好的，这次没问题了，就是要把mavenCentral放到阿里的前面，这个好像是从阿帕奇上下下来的，我之前不用阿里的时候从上面下一些官方的依赖会超时下不下来😂
https://repo.maven.apache.org/maven2/com/github/javakam/widget.optionview/6.0.0/widget.optionview-6.0.0.aar

**Comment by javakam** [comment]
更新了下说明, 更清楚了

![image](https://user-images.githubusercontent.com/15343661/233251945-aec55581-abd7-4fcb-8202-aa1c11408dfb.png)

**Comment by SaltedFish-Extreme** [comment]
好的👌
