### ISSUE TITLE
老哥，我刚才更新Android Studio之后升级了gradle版本，依赖重新下了，你的库还是不行啊

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [javakam/DialogManager#3]
![image](https://github.com/javakam/DialogManager/assets/54784104/523b9e76-b718-414e-adf6-ca5960017ab2)

![image](https://github.com/javakam/DialogManager/assets/54784104/fa9ba203-b778-4be7-82fe-de9dd9735b72)

为啥阿里云下不下来这个库😂

**Comment by javakam** [comment]
直接拷贝吧，没几个类

**Comment by SaltedFish-Extreme** [comment]
😂好吧
