### ISSUE TITLE
老哥，有个问题，弹窗显示中，如果切换夜间模式，当前页面被重建了，再打开弹窗会闪退

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [javakam/DialogManager#5]
java.lang.IllegalArgumentException: View=DecorView@4d6422e[修改昵称] not attached to window manager

![image](https://github.com/javakam/DialogManager/assets/54784104/4562be5f-8768-4978-b755-8527c0ce5fde)

**Comment by javakam** [comment]
贴下代码吧, 我不清楚具体的操作流程。盲猜是切换夜间模式导致重建Activity, Dialog就跟着出问题了, 试一试Application的Context行不行

**Comment by SaltedFish-Extreme** [comment]
@javakam 我用application的context直接空指针了😂

![image](https://github.com/javakam/DialogManager/assets/54784104/c849c659-5885-4668-a74c-5927d03d08b1)

**Comment by SaltedFish-Extreme** [comment]
就是复制demo中显示输入对话框的方法，直接复制的，没怎么改

**Comment by SaltedFish-Extreme** [comment]
@javakam 老哥，我用你的程序运行了一下demo，也是这样，我发个视频，你看一下

https://github.com/javakam/DialogManager/assets/54784104/c617abac-91ad-44ba-9017-cc24b5ad4fc8

**Comment by SaltedFish-Extreme** [comment]
我感觉好像是页面销毁重建的时候，这个弹窗的实例没销毁，我之前用轮子哥吐司框架的时候也有这个问题，他也是用的这种附加弹窗当作吐司，后来他修复了，当时好像还有内存泄漏的问题，这个弹窗在切换夜间模式之后，占的内存没释放掉😂

**Comment by javakam** [comment]
Activity中加上
```
 override fun onDestroy() {
        super.onDestroy()
        DialogManager.dismiss();
    }
```
就好了...

**Comment by SaltedFish-Extreme** [comment]
😂可以，麻烦了
