### ISSUE TITLE
老哥，请问这个单选弹窗的item样式可以调整吗😂好像没有适配夜间模式，还有这个默认不选中有属性设置吗？我看打开弹窗默认选中第一个，想不设置默认选中，或者默认选中哪个，有设置的方法吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [javakam/DialogManager#7]
![image](https://github.com/javakam/DialogManager/assets/54784104/e970abb2-ab17-4d36-b90d-dc9f96f9c715)

![image](https://github.com/javakam/DialogManager/assets/54784104/9d19ecd1-9e8e-4005-b6c4-97907e72dc1b)

**Comment by SaltedFish-Extreme** [comment]
我照着demo写的，都设置ischecked=false，还是默认选中第一个

![image](https://github.com/javakam/DialogManager/assets/54784104/a2d6ecb4-1413-4e92-b205-eaa5e1e0e407)

**Comment by SaltedFish-Extreme** [comment]
我把布局复制出来改了下，可以适配夜间主题了，但是还是会默认选中第一个，这个不知道怎么搞，老哥有办法吗😂

**Comment by SaltedFish-Extreme** [comment]
我看老哥好像在这设置了默认选中第一个，能不能加个属性，可以不设置默认选中哪一个，然后可以修改默认选中哪一个😂

![image](https://github.com/javakam/DialogManager/assets/54784104/79e80c79-88f9-402a-84b1-623809cb110d)

**Comment by javakam** [comment]
设计时候考虑到这个情形了... 但是忘记写实现, v7.5.0已经加上
![image](https://github.com/javakam/DialogManager/assets/15343661/ea33975a-2d6d-47b3-b65b-ab79c2365411)

**Comment by javakam** [comment]
isCheckAllowNothing=true

**Comment by javakam** [comment]
改日再优化下代码, 其实这个参数是不需要的, 可以暂时用着

**Comment by SaltedFish-Extreme** [comment]
😂好的，麻烦了老哥，这个弹窗框架真的挺方便的，底部弹窗输入弹窗和日期选择弹窗还有单选弹窗都用上了，我网友也看日期选择弹窗UI好看，也来用了😋

**Comment by SaltedFish-Extreme** [comment]
@javakam 老哥，话说现在选第一个选项没有用了，没走onItemSelected监听回调，选了没有用了，再打开弹窗还是都没选中的状态😂

**Comment by SaltedFish-Extreme** [comment]
![image](https://github.com/javakam/DialogManager/assets/54784104/ff6f7613-86a1-4f5e-a1d8-623ea172db00)

我看好像是这个地方，应该是>=0😂

**Comment by javakam** [comment]
可以了, 把`isCheckAllowNothing`删除了 👉 `v7.6.0`

**Comment by SaltedFish-Extreme** [comment]
好的，没问题了，麻烦老哥了😘

**Comment by javakam** [comment]
小事情, 客气
